### ISSUE TITLE
[UT] - Dichoso | Profile Units Not Adhering to coding standards

### ISSUE THREAD

**Issue by ADichoso** [ADichoso/STSWENG_XX22_G1#1]
**Unit Test Info**
Add the following information
1. profile.test.js
2.  Profile Controller
3. Tests:
**get_profile suite:**
_'should redirect user profile page with details of session user if session.id_number != query.id_number'
'should redirect admin profile page with details of session admin if session.id_number != query.id_number'
'should redirect driver profile page with details of session driver if session.id_number != query.id_number'_

**get_profile_admin suite:**
_'should redirect to admin page if session.id_number != query.id_number'
'should redirect to user page if session.id_number != query.id_number and session id is a user
'should redirect to driver page if session.id_number != query.id_number and session id is a driver'_

**get_profile_driver suite:**
_'should redirect to driver page if session.id_number != query.id_number'
'should redirect to user page if session.id_number != query.id_number and session is a user'
'should redirect to admin page if session.id_number != query.id_number and session is a admin'_

**post_change_password suite:**
_"should change a user's password if the old password is correct"
"should change an admin's password if the old password is correct"
"should change the driver's password if the old password is correct"
"should redirect to the settings page if the action is unsuccessful"_

**entire post_change_code suite:**

**Describe the concern**
In all specified unit tests, the projection format being request is in the form of a JSON object. However, from SCRUM meetings, it was agreed upon that database operation projections are to be in a string format. Please change the format of the unit tests accordingly.

**Expected behavior**
Upon changing the format, the code of the developers should result in accepted tests.

**Screenshots**
**Unit Test Projection Format**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/39649018/0f09e635-bf0c-4270-b9b3-5a7a7222fff8)

**Developer Projection Format**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/39649018/1069d8ae-f26b-4ec6-b73d-6be10e44cb18)

**Comment by Lunarianerino** [comment]
This have been fixed in the latest push in the [Profile Tests Branch](https://github.com/ADichoso/STSWENG_XX22_G1/tree/QA_LuisAustin/ProfileTests). Thank you!

**Comment by Lunarianerino** [comment]
Closing this report now as it has been fixed

**Comment by austinatividad** [comment]
This should now be fixed in the [latest commit](https://github.com/ADichoso/STSWENG_XX22_G1/commit/6381f1982b7fc61e4d85eb19f65340038619f45e). Thank you!
