### ISSUE TITLE
[BUG] - Natividad | Sign Up Page Incorrect Error Message (Automated Test 1-7)

### ISSUE THREAD

**Issue by austinatividad** [ADichoso/STSWENG_XX22_G1#10]
**Describe the bug**
When a user leaves their ID number blank, the error message shown should be "ID Number should not be empty." instead of "ID 
number should not be empty."

**To Reproduce**
1. Go to `/SignUp`
2. Enter all valid information except ID number
3. Click ID number and press `backspace`

**Expected behavior**
When a user leaves their ID number blank, the error message shown should be "ID Number should not be empty." instead of "ID 
number should not be empty."

**Screenshots**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/be9e9baf-67ab-49ea-a293-3391b950666e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123

**RobotFramework Report**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/6d2cd3d1-c3b8-4c2d-bde0-e59013ec371c)

**Comment by ADichoso** [comment]
Hello Austin, all of the automated tests in the integration branch have been checked and are passing. Closing this thread.
