### ISSUE TITLE
[BUG] - Natividad | Empty Password has no Error Message (Automated Test 1-9)

### ISSUE THREAD

**Issue by austinatividad** [ADichoso/STSWENG_XX22_G1#11]
**Describe the bug**
When a user is signing up, if they leave their password empty, there will be no error.

**To Reproduce**
1. Go to `/SignUp`
2. Enter all valid information, but leave the password blank.
3. Trigger validation: click the password input box
4. Enter `backspace`
6. See lack of error message

**Expected behavior**
The user should be informed that the signup button is disabled because they did not write a password.

**Screenshots**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/1e861c8f-9f3d-4994-bd3d-936d0c621c1a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123

**RobotFramewok Report*
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/a1c3cc8a-288a-4ccf-81dc-f520b0b8d774)

**Comment by ADichoso** [comment]
Hello Austin, all of the automated tests in the integration branch have been checked and are passing. Closing this thread.
