### ISSUE TITLE
[BUG] - Natividad | Schedule Incorrect Error Handling (Automated Test 4-3 Missing Date)

### ISSUE THREAD

**Issue by austinatividad** [ADichoso/STSWENG_XX22_G1#12]
**Describe the bug**
The schedule form goes through despite having the date left empty. It results in a visual glitch that can be seen below.

**To Reproduce**
**Assume user is logged in**
1. Go to `Schedule`
2. Click the `View Schedule` button
3. Fill up Form but leave the date blank

**Expected behavior**
The page should display an error message informing the user that they must fill in all the fields.

**Screenshots**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/1b088d09-b02d-4bc2-973e-74e6d27c3c85)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123

**RobotFramework Report**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/13a81a12-8dfa-4aa5-8741-c03a38b690a6)

**Comment by ADichoso** [comment]
Hello Austin, all of the automated tests in the integration branch have been checked and are passing. Closing this thread.
