### ISSUE TITLE
[BUG] - Razon | ReservationAdmin page is accessible by a normal User

### ISSUE THREAD

**Issue by Lunarianerino** [ADichoso/STSWENG_XX22_G1#13]
As a user account, I am able to access the Reservation Admin Page as long as it fulfills the condition session user_id = query user_id

1. Login using a User Account
2. Click on Profile (for convenience, but you can access it anywhere)
3. Replace "Profile" in the URL with "ReservationAdmin"
4. See the page load

As a user, I should not have access to this page as it is only meant for admins and drivers

![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/cbdc5007-3796-4d78-9841-7242ae40614c)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/7e95ba72-5220-4162-b984-a8ba0c257130)

Desktop:
 - OS: Windows 11
 - Browser: Google Chrome
 - Version 123.0.6312.59 (Official Build) (64-bit)

**Comment by ADichoso** [comment]
Thank you Luis, this issue has been resolved on the dev branches, Closing this thread.
