### ISSUE TITLE
[BUG] - Razon | Forgot Password Page not working

### ISSUE THREAD

**Issue by Lunarianerino** [ADichoso/STSWENG_XX22_G1#14]
When using Forgot Password page and entering the correct details, it does not move on and it notifies me that my inputs are invalid.

1. Go to "/ForgotPassword"
2. Enter the correct details (for this example email is "luisrazon1121@gmail.com" and security code "1234"
3. Click submit
4. See the notification pop-up and the page does not move on to the next step

Expected Behavior:
Since the details I input are correct, I should be prompted to change my password.

![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/0ad32cb4-0b4a-4a85-95d3-2ec3d57a37a9)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/5e7adf69-1b19-4db3-b4ee-3a451741a22d)

Proof that details are correct:
(From EditDriver Page)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/dab58b4e-06f2-4b59-8ab6-6965abfc009b)

(Logging in using the account)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/543c5aa6-ab0f-452a-af1b-9f5db8c8dfd8)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/209b5f95-c1d4-4ea6-b205-5a96b863f309)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/c705db14-575e-4600-9ab8-06c95399ae03)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: Version 123.0.6312.59 (Official Build) (64-bit)

**Comment by ADichoso** [comment]
Thank you for this concern Luis, it has now been resolved. Closing this thread.
