### ISSUE TITLE
[BUG] - Razon | Security Code is not working as intended

### ISSUE THREAD

**Issue by Lunarianerino** [ADichoso/STSWENG_XX22_G1#2]
The users are able to completely bypass security code check which presents a security risk.

1. Go to "/Login"
2. Enter correct login details (username and password). This would lead the user to "/Security?id_number=[idnumber]"
3. Use any method to get to profile without having to enter a security code
3.1. Replace "Security" with "Profile", "ProfileAdmin", or "ProfileDriver" in the url
3.2. Click the DLSU Logo then click the name of the profile on the top right

What is expected to happen is that the user should not be considered as "Logged In" wherein they are able to access the accounts while they have not entered the correct Security Code.

![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/25c57756-ab0c-437c-8a68-45fd0573c62f)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/c1486d4b-5c82-4992-8bee-38a6ec729555)
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/71534058/6956ebf8-478f-4c53-8e39-7b8ddae3b98e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome

I feel like this is happening because the session is being set upon successful entry of username and password even if there is still the security code check

**Comment by ADichoso** [comment]
Hello Luis. This bug is noted. Will address it and apply changes immediately. Thank you

**Comment by ADichoso** [comment]
This issue has now been fixed in the Staging Branch. Thank you.
