### ISSUE TITLE
[BUG] - Natividad | Invalid access to /SecurityCheck

### ISSUE THREAD

**Issue by austinatividad** [ADichoso/STSWENG_XX22_G1#4]
**Describe the bug**
Users can skip logging in and use the URL bar to navigate to /SecurityCheck. Entering the correct PIN will break the website, presented with the error `ERR_TOO_MANY_REDIRECTS.` 

**To Reproduce**
1. Go to `/SecurityCheck?id_number={insert valid ID number}`
2. Enter the correct Security PIN
3. See error

**Expected behavior**
The user who has not yet logged in should be unable to access this part of the website and should probably be redirected to `/Login` instead.

**Screenshots**
![Screenshot 2024-03-07 195251](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/49cb3f7a-aa8f-47e7-af57-9e5f3f9537b8)

![Screenshot 2024-03-07 195445](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/62a53cff-f77b-4ad0-a8eb-81aa43ef9bfe)

![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/834d1ba1-971a-4265-9390-4225a03bdf57)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 122

**Comment by ADichoso** [comment]
Thank you for this Josh. As of writing, this issue has been resolved. Closing this issue.
