### ISSUE TITLE
[BUG] - Natividad | Incorrect Title Spelling

### ISSUE THREAD

**Issue by austinatividad** [ADichoso/STSWENG_XX22_G1#7]
**Describe the bug**
The name displayed in `/` is `Arrow Express`; however, the correct spelling is `Arrows Express`.

**To Reproduce**
1. Go to `localhost:3000/`

**Expected behavior**
The webpage should display the correct details.

**Screenshots**
![image](https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/22a176b5-3dcf-45e6-a616-ac16ddbc1e95)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 122
 - Branch: staging

**Comment by ADichoso** [comment]
Fixed this issue, Josh. Thank you. Closing this issue.
