### ISSUE TITLE
[BUG] - Natividad | Incorrect Spelling of Browser Title Bar

### ISSUE THREAD

**Issue by austinatividad** [ADichoso/STSWENG_XX22_G1#8]
**Describe the bug**
The spelling of `Arrows Express` on many pages is incorrect as it is spelled as `Arrow Express.`
Please take a look at the screenshot below for examples of web pages that fall under this error.

**To Reproduce**
1. Go to `/`
2. Go to `/login`

**Expected behavior**
The web pages should display the correct content.

**Screenshots**
<img width="251" alt="Screenshot 2024-03-15 at 2 50 43 PM" src="https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/d30065a8-0439-4564-8127-dbf3272319a4">
<img width="277" alt="image" src="https://github.com/ADichoso/STSWENG_XX22_G1/assets/114718588/b43226b2-9904-4f4d-b4f6-7d76348b0299">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 122
 - Branch: Staging

**Comment by ADichoso** [comment]
Fixed this issue; closing the thread.
